import type { APIRoute } from 'astro';

/**
 * /sitemap.xml — the address most people (and Search Console) try first. The real sitemap is
 * generated by @astrojs/sitemap as /sitemap-index.xml → /sitemap-0.xml; this serves the same
 * sitemap index at the conventional path so either submission works.
 */
export const GET: APIRoute = ({ site }) => {
  const loc = new URL('/sitemap-0.xml', site).href;
  const body = `<?xml version="1.0" encoding="UTF-8"?><sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><sitemap><loc>${loc}</loc></sitemap></sitemapindex>`;
  return new Response(body, { headers: { 'Content-Type': 'application/xml; charset=utf-8' } });
};
